version: "3"
services:
  nginx:
    ports:
      - "80:80"
    restart: unless-stopped
  node-app:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    deploy:
      replicas: 2
    restart: unless-stopped
    command: node index.js
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped

  redis:
    restart: unless-stopped